### ISSUE TITLE
Cannot build libjitsi: CryptoBenchmark still references deleted NIOBlockCipher class

### ISSUE THREAD

**Issue by pete-by** [jitsi/libjitsi#132]
Maven build failed due to unresolved class NIOBlockCipher used in CryptoBenchmark:

```
NIOBlockCipher nioBlockCipher
                    = (blockCipher instanceof NIOBlockCipher)
                        ? (NIOBlockCipher) blockCipher
                        : null;
```

[CryptoBenchmark.java:163](https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/transform/srtp/CryptoBenchmark.java#L163)

Class was deleted month ago: https://github.com/jitsi/libjitsi/commit/18c951646db8d748f17d6aaeb7feec37439266f9#diff-2d6e07f58eb241e2530d748450b72b6a

**Comment by champtar** [comment]
see #133

**Comment by lyubomir** [comment]
> Maven build failed due to unresolved class NIOBlockCipher used in CryptoBenchmark

Do you know how the Maven build did that given that CryptoBenchmark is explicitly excluded?

**Comment by champtar** [comment]
Indeed, i've no idea ...
Should i still exclude it in maven

**Comment by pete-by** [comment]
Sorry for misleading, it was project build problem in IDE after importing it from Maven model.
