### ISSUE TITLE
C# Implementation of Libjitsi: Capturing Desktop using WebRTC 

### ISSUE THREAD

**Issue by Raj123456788** [jitsi/libjitsi#168]
Hello There, I just started doing research on Jitsi- VideoBridge and I am developing a desktop sharing application( Live streaming Audio & Video) which can run on all the platforms natively using WebRTC. Jitsi is all written in JAVA and can someone share/guide me C# implementation of Jitsi. I would also like to know what Frames/sec does jitsi offer for 1080p resolution. Let me know any other info is required.

**Comment by ibauersachs** [comment]
There's no C# version of Jitsi.
