### ISSUE TITLE
Recording RTP VP8 to webm

### ISSUE THREAD

**Issue by ffalanga** [jitsi/libjitsi#170]
Hi,
I have implemented a java application, that read RTP packet saved with wireshark (pcap file).
I'm able to read the RTP with VP8 codec (payload type = 120).
How I can save a webm file from them?
Please can you help me?

Thanks in advance
Francesco

**Comment by gpolitis** [comment]
Hi Francesco, we don’t have anything that works off the shelf. Assuming the pcap file is decrypted (typically, if it’s webrtc traffic, it’s encrypted), you can use libjitsi to write a program that does the conversion or use gstreamer.

I'm not sure about the exact gstreamer syntax, but according to [this](http://stackoverflow.com/questions/24530911/gstreamer-rtpvp8depay-cannot-decode-stream), it should look like something like this `gst-launch-0.10 filesrc location = myPipe ! capsfilter caps = application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)VP8-DRAFT-IETF-01, payload=(int)96 ! rtpvp8depay ! vp8dec ! ffmpegcolorspace ! autovideosink`.

Also, please keep in mind that it's best to address this kind of questions to our dev mailing list :)
