### ISSUE TITLE
dropMutedAudioSourceInReverseTransform=false should avoid recorded splitting audio file

### ISSUE THREAD

**Issue by zbettenbuk** [jitsi/libjitsi#194]
@gpolitis @bgrozev Hi guys,

You showed me that this system setting should avoid VideoBridge to split the recorded audio file to parts on mute, but doesn't really work. I checked the code and it seems so that there is actually no such functionality.

Do you think adding a boolean variable to enable/disable the resetRecording(ssrc, timestamp) (RecorderRtpImpl.java:761) call would cause any side effect? If not, I'd implement it

Thx,
Zoli

**Comment by bgrozev** [comment]
> Do you think adding a boolean variable to enable/disable the resetRecording(ssrc, timestamp) (RecorderRtpImpl.java:761) call would cause any side effect?

I'm not sure I understand what you're proposing. If the onSilenceNotInserted event fires, and we don't reset the file, audio/video sync will be broken.

If you are seeing splits this means packets not reaching the recorder for some reason, and you should find out why and address it.
