### ISSUE TITLE
Using Libjitsi on server with no audio device

### ISSUE THREAD

**Issue by mcacker** [jitsi/libjitsi#202]
Hi, 

I would like to use libjitsi in an application on a server that has no audio device.  The use case is to capture the audio via a SIP leg to a media server, and then process the audio using the libjitsi library.

When I attempt to run the app on the server with no audio device the library fails to start.   Is there a way to turn off device detection or install a null device of some sort?

thanks, Mitchell

**Comment by ibauersachs** [comment]
Have a look at how [Jigasi](https://github.com/jitsi/jigasi) is implemented. It does exactly what you want (take calls, forward it to the Videobridge).

**Comment by mcacker** [comment]
Thanks for the suggestion, however, it doesn't do what I want.  

My application is going to be doing the media processing itself, using the libjitsi library, and that is where I can run into issues as Libjitsi performs device discovery and if there are no devices, or no media processing libraries, e.g., certain flavors of unix, it won't work.  I would like to turn off device discovery if possible and not use the devices at all.

**Comment by lyubomir** [comment]
@mcacker, https://github.com/jitsi/jitsi-videobridge & https://github.com/jitsi/jicofo are server-side applications which utilize https://github.com/jitsi/libjitsi and do not require audio devices. Please look at https://github.com/jitsi/jicoco/blob/master/src/main/java/org/jitsi/meet/OSGiBundleConfig.java#L147 to see how these 2 lift the requirement of both audio and video devices.
