### ISSUE TITLE
Wrapper error when using android 5.0

### ISSUE THREAD

**Issue by phutang2359media** [jitsi/libjitsi#26]
Hi guys,
I not sure this problem is relative with your source code or not. If you have time, please help me. I'm using for wrapper file to build an opus codec lib. For more detail in here. 
http://stackoverflow.com/questions/27355052/java-lang-unsatisfiedlinkerror-when-using-with-android-5-0
 
Overall: with your wrapper and source code from opus-codec.org, it work perfect on android 4.0+ but in Android 5.0 it can't find any native method and this is the exception: java.lang.UnsatisfiedLinkError: No implementation found for ... let me know if you have solution or reply in stackoverflow. 

Best regards,

**Comment by yanas** [comment]
The question has been answered on stackoverflow: http://stackoverflow.com/questions/27355052/java-lang-unsatisfiedlinkerror-when-using-with-android-5-0.
