### ISSUE TITLE
Read IP Camera using RTSP protocol

### ISSUE THREAD

**Issue by ghostidentity** [jitsi/libjitsi#278]
Hello,

Its been days since im looking for solution to decode h264 codec from IP camera video stream for facial detection purpose.

Does libjitsi the right solution ? If so, is there a sample code for me to try.

Thanks,
Mark

**Comment by saghul** [comment]
Hi Mark,

I think you are better suited using OpenCV or SimpleCV. libjitsi wasn't designed for such purpose.

Cheers,

**Comment by ghostidentity** [comment]
Hello, 

I tried openimaj and was able to access live video stream from IP camera. However,  I have serious problem on processing high video resolution.

I already tried OpenCV but was not satisfied with performance because it was optimized for C++. Ill try SimpleCV some other day.

Thanks,
Mark

**Comment by Gopinathp** [comment]
Does this library support RTSP streaming?

**Comment by bgrozev** [comment]
No, it doesn't.
