### ISSUE TITLE
VPXDecoder sets TIME_UKNOWN on the output buffer

### ISSUE THREAD

**Issue by mondain** [jitsi/libjitsi#28]
On lines 170 and 220, the output buffer has its timestamp set to Buffer.TIME_UNKNOWN or -1 instead of simply copying the input buffer timestamp or using the PTS or DTS from the native decoder.

https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/codec/video/vp8/VPXDecoder.java

Setting this value to unknown causes issues for implementers wanting to re-encode or use the frames in follow up processing.

**Comment by bgrozev** [comment]
Fixed with merging  PR #31
