### ISSUE TITLE
read queue is ful

### ISSUE THREAD

**Issue by nghiatrongnguyen** [jitsi/libjitsi#29]
when I use ofmeet the server generates this error

Dec 18, 2014 10:31:38 AM org.jitsi.util.Logger warn
WARNING: Discarded an RTP packet because the read queue is full.
Dec 18, 2014 10:31:38 AM org.jitsi.util.Logger info
INFO: Stream: 272742f8ef1ed8a1, RTT computation may be wrong (65536>= 65536 milliseconds): now 14188

It causes miscommunication when points connect to server (loose audio or video)
I checked the source code of jitsi and found that the error may be generated from this
libjitsi/PushSourceStreamImpl.java at master · jitsi/libjitsi · GitHub
and the MaxPacketsPerMillisPolicy.PACKET_QUEUE_CAPACITY is read from configuration file.
However, I couldn't find the configuration file for it.

Any one know where is it defined?

**Comment by yanas** [comment]
@nghiatrongnguyen we have fixed some of the things that could be causing this one. If you have been using TCP then this commit 7f39f55 may fix the issue. Also this could be normal in the case where the machine is overloaded. Please reopen if the issue persists with the newest version.
