### ISSUE TITLE
DTLS, unsecure cipher suites (SHA-1)

### ISSUE THREAD

**Issue by flurbi** [jitsi/libjitsi#292]
org.jitsi.impl.neomedia.transform.dtls.TlsClientImpl.getCipherSuites()
    org.jitsi.impl.neomedia.transform.dtls.TlsServerImpl.getCipherSuites()
        Consider removing SHA-1 cipher suites.

**Comment by ibauersachs** [comment]
I can't find a definitive list of ciphers that are supported in Chrome or Firefox. SHA1 should probably not be there in any case, and Chrome/Safari [removed support for DHE ciphers completely](https://crbug.com/619194).

[draft-ietf-rtcweb-security-arch-13](https://tools.ietf.org/html/draft-ietf-rtcweb-security-arch-13) mandates support of TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (questionable, and [Chrome doesn't support it](https://bugs.chromium.org/p/chromium/issues/detail?id=655318) anyway) and TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, but we don't support any ECDHE_ECDSA yet.

**Comment by 2357mam** [comment]
Hi @ibauersachs, the issue is closed but doesn't link to a commit or pr. Was this fixed?

**Comment by ibauersachs** [comment]
Most of the changes are in commit 60f54cce9ca719f9d6b6bd1489e73f9966d0ca8a
