### ISSUE TITLE
JNI, malloc, null-pointer cast to jlong incorrectly assumed to be 0

### ISSUE THREAD

**Issue by flurbi** [jitsi/libjitsi#293]
openssl/HMAC.c
    openssl/SRTPCipherCTROpenSSL.c
    portaudio/org_jitsi_impl_neomedia_portaudio_Pa.c
    speex/org_jitsi_impl_neomedia_codec_audio_speex_Speex.c
    linux/pulseaudio/org_jitsi_impl_neomedia_pulseaudio_PA.c
    linux/video4linux2/org_jitsi_impl_neomedia_jmfext_media_protocol_video4linux2_Video4Linux2.c
    jawtrenderer/JAWTRenderer_Linux.c
    vpx/org_jitsi_impl_neomedia_codec_video_VPX.c
        If malloc fails, 0 should be returned (checked on the java side).
        Problem: a null pointer cast to an integer is not necessarily 0.

**Comment by ibauersachs** [comment]
None of the supported platforms do the weird (but C standard conformant) null-pointer-is-not-0 thing. If you /really/ want to address this, please open a pull request.
