### ISSUE TITLE
Opus decoding problems

### ISSUE THREAD

**Issue by digiology** [jitsi/libjitsi#3]
I'm using libjitsi's Opus class in a project. It works perfectly with version 212, before the outputOffset was added to Opus.encode() and Opus.decode(). I've tried the later version 266 and changed my code to include an outputOffset (which I've simply set to zero) but I'm getting problems, Opus.decode() is returning -1.

Two questions:
-Are there any tests for this class to be sure Opus is working and its not just me making a mistake?
-Are there any plans to for the Opus class to provide more information about problems during encode/decode? A general -1 error code without no console output is very unhelpful.

**Comment by yanas** [comment]
Currently we don't have unit tests for Opus. Please feel free reopen if you're still experiencing the problem with the current code base.
