### ISSUE TITLE
How to mix two audio files,like two aac files?

### ISSUE THREAD

**Issue by chenweitracy** [jitsi/libjitsi#33]
Is there a java method in this project to mix two audio files?
Thanks.

**Comment by lyubomir** [comment]
There is NO java method in this project to mix two audio files.

**Comment by chenweitracy** [comment]
Sorry,but I've found a class AudioMixer.java.Is this class can mix audio files?

**Comment by lyubomir** [comment]
The class AudioMixer CANNOT mix audio files.

**Comment by mondain** [comment]
An audio "mixer" is not meant as a means for merging audio samples, it is more or less a router of audio. For instance consuming audio from a microphone and directing it to speakers.

**Comment by chenweitracy** [comment]
Oh I see, Thanks

**Comment by fabvador** [comment]
Is it possible to send the incoming RTP stream on a loudspeaker and headset simultaneously?
