### ISSUE TITLE
MP3 recording crashes in FFmpeg

### ISSUE THREAD

**Issue by lyubomir** [jitsi/libjitsi#34]
Damian Minkov and Ingo Bauersachs reported the attempting to record calls in Jitsi on certain old versions of OS X and recent version of Windows crashes the process.

OS X crash log provided by Damian Minkov: http://pastebin.com/guS4hNrN

**Comment by damencho** [comment]
OS X crashes fixed with commit 6bf27dfd3a9d16691588ff940f53e6cb9f287983.

**Comment by lyubomir** [comment]
Windows crash logs provided by Ingo Bauersachs: http://pastebin.com/rcH0xF8f, http://pastebin.com/FGuc2u6X.
