### ISSUE TITLE
OpenSSL HMAC-SHA1 crashes Jitsi Videobridge

### ISSUE THREAD

**Issue by lyubomir** [jitsi/libjitsi#35]
Boris Grozev has reported a crash in Jitsi Videobridge which appears to be caused by the OpenSSL HMAC-SHA1 JNI implementation: http://pastebin.com/Em2SrZkU

**Comment by jitsi-developers** [comment]
Got the same error using the last commit of Jitsi Videobridge:

[thread 140532624729856 also had an error]#

# A fatal error has been detected by the Java Runtime Environment:

#

#  SIGSEGV (0xb) at pc=0x00007fd0088ba28a, pid=2027, tid=140532641572608

#

# JRE version: OpenJDK Runtime Environment (7.0_65-b32) (build 1.7.0_65-b32)

# Java VM: OpenJDK 64-Bit Server VM (24.65-b04 mixed mode linux-amd64
compressed oops)

# Derivative: IcedTea 2.5.2

# Distribution: Ubuntu 14.04 LTS, package 7u65-2.5.2-3~14.04

# Problematic frame:

# C  [libcrypto.so.1.0.0+0xea28a]# [ timer expired, abort... ]

/usr/share/jitsi-videobridge/jvb.sh: line 32:  2027 Aborted
(core dumped) LD_LIBRARY_PATH=$libs java -Xmx$VIDEOBRIDGE_MAX_MEMORY
$VIDEOBRIDGE_DEBUG_OPTIONS -XX


Regards,

Zalmoxisus

**Comment by jitsi-developers** [comment]
Update: In may case it occurs only when useRtcpMux is enabled.

**Comment by bgrozev** [comment]
Presumed fixed with https://github.com/jitsi/jitsi-videobridge/commit/473f24edee95b6d0432f13d51b5b500a0a22c0bb and https://github.com/jitsi/libjitsi/commit/6065f503917fa9696aee117d11309963899e80a7
