### ISSUE TITLE
Are there plans to support VP9?

### ISSUE THREAD

**Issue by naive924** [jitsi/libjitsi#388]
DePacketizer seems to be already implemented.
https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/impl/neomedia/codec/video/vp9/DePacketizer.java

**Comment by gpolitis** [comment]
With proper signaling from jicofo, plain VP9 (no SVC) should work fine. You can, for example, modify Jicofo to remove all other codecs https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java.

If that is not working, please feel free to re-open this issue.
