### ISSUE TITLE
Single NALU length calculation for H264 leads to video corruptions

### ISSUE THREAD

**Issue by avila-devlogic** [jitsi/libjitsi#400]
This turns out to be an issue with this commit c8bf4692d9e692bde2a759ed2b6d8434375113bd

Fix miss-interprets len parameter when calculating NALU payload length represented by naluLength.
len parameter is length of buffer regardless of offset while offset is position where NALU payload starts within that buffer.

Hence, naluLength should be equal to len - offset - naluHeaderSize, or simply as it was len - naluStart

That produces corruptions as it bails out of keyframe recognition due to allegedly malformed StapA payload and doesn't forward the first keyframe when switching simulcast layers but forwards subsequent delta frames of layer it switched to.

**Comment by bbaldino** [comment]
thanks @avila-devlogic, want to open a pr?  @gpolitis any thoughts?

**Comment by gpolitis** [comment]
> len parameter is length of buffer regardless of offset

That's incorrect, the `len` parameter is the length of the data in the buffer. The length of the buffer, regardless of offset is `buffer.length`.

If you experience video corruption, there must be some other bug somewhere. Could you please elaborate a bit more on what you're experiencing?

**Comment by avila-devlogic** [comment]
@gpolitis Please take a look at isKeyFrame signature @L515. It explicitly says `the length of the data in the byte buffer`. Maybe wording should be bit better as we've relied on it.

**Comment by gpolitis** [comment]
We can definitely rephrase this if you feel it's confusing and you can suggest a less confusing wording. Please feel free to open a PR for that.

We're also happy to help you with the issue you're experiencing, if you can share a few more bits on that.

**Comment by avila-devlogic** [comment]
@gpolitis , thanks for a pushback. That made me dig a bit deeper and I've found that we had wrong merge of c0290b05d87daf13fbf1d5b47627e9825337cc29 that changed from RTP packet size to it's payload size

Hence this issue is non-existent in the current codebase

**Comment by gpolitis** [comment]
I'm glad you solved the problem! Please let us know if you have any other problems with H264 simulcast; this is not a scenario we're actively testing, but we're more than happy to help you solve any issues that you're facing.
