### ISSUE TITLE
Can not connect to camera in Windows environment( x86 and x64 / H264, VP8, VP9 all do not work). libjitsi is causing, jitsi is not a problem.

### ISSUE THREAD

**Issue by spf-tanabe** [jitsi/libjitsi#431]
## Description
*  When connecting to the camera with Nightly Builds (x86 and x64), the screen turns black
 * ![image](https://user-images.githubusercontent.com/41299235/42767761-cf9d7a42-8958-11e8-8ebb-eca4c73614a8.png)
* Reproduce with all the following builds
  * https://download.jitsi.org/jitsi/nightly/windows/
```
jitsi-2.11.5604-x86.exe           2018-04-14 03:23   62M
jitsi-2.11-nightly.latest-x86.exe 2018-04-14 03:23   62M
jitsi-2.11.5604-x64.exe           2018-04-14 03:22   63M
jitsi-2.11-nightly.latest-x64.exe 2018-04-14 03:22   63M  
```
* Even Nightly Builds, the Mac worked correctly.

## Steps to reproduce
* Jitsi (Nightly Builds) can reproduce 100%.
* This problem was confirmed by the following sample code that libjitsi is causing, jitsi is not a problem.
* This problem does not reproduce when commit is reverted until about February 2017, and sample code also works correctly.
* ![image](https://user-images.githubusercontent.com/41299235/42771619-c0d4f09e-8962-11e8-9e8c-40e17f9bb643.png)

```
LibJitsi.start();
List<MediaDevice> devices = ((MediaServiceImpl) LibJitsi.getMediaService()).getDevices(MediaType.VIDEO,
        MediaUseCase.CALL);
MediaDevice device = devices.get(0);

JFrame f = new JFrame();
Component comp = (Component) LibJitsi.getMediaService().getVideoPreviewComponent(device, 640, 480);
f.getContentPane().add(comp, BorderLayout.CENTER);
f.pack();
f.setVisible(true);
```

# Environment details
* Jitsi 2.11.5604 Nightly Builds
* libjitsi is the master branch (From around 2017-02) 
  * From what time this phenomenon occurs, details unknown
* Windows10 x64
  * We can not check the operation of Windows 7
* Java version 1.8.0 and above

**Comment by spf-tanabe** [comment]
Hi @ibauersachs  @gpolitis @bgrozev @bbaldino 
This problem may be caused by the following pull request.
https://github.com/jitsi/libjitsi/pull/403

Because I confirmed that this commit works correctly.
```
$ git log
commit 45c6fb7bdbc61f469666a540b399b8232d5a9e1b (HEAD, tag: 1036)
Merge: 2015b273 dc36e5f4
Author: Ingo Bauersachs <ingo@jitsi.org>
Date:   Mon Feb 19 14:17:11 2018 +0700
```
![image](https://user-images.githubusercontent.com/41299235/42827205-e2e9a7b0-8a20-11e8-9c0f-549da05fcd27.png)

**Comment by damencho** [comment]
@spf-tanabe Did you install openh264?
<img width="568" alt="screen shot 2018-07-17 at 10 37 17" src="https://user-images.githubusercontent.com/3263098/42828030-664576da-89ad-11e8-8f26-d9cd5f974361.png">

**Comment by spf-tanabe** [comment]
@damencho 
> Did you install openh264?

Thank you for your advice!
Yes. I reconfirmed the download of openh 264, but the situation has not changed.

- Step1 : Download
![image](https://user-images.githubusercontent.com/41299235/42830322-0a6986a2-8a26-11e8-8a24-f8a7628fe7a7.png)
- Step2 : Restart Jitsi
- Step3 : h264 is active
![image](https://user-images.githubusercontent.com/41299235/42830420-54872884-8a26-11e8-94ca-8256e4dd850e.png)
- Step4 : the screen turns black. (H264, VP8, VP9, other )
![image](https://user-images.githubusercontent.com/41299235/42830440-6678a838-8a26-11e8-8622-8e474460a780.png)

**Comment by spf-tanabe** [comment]
For your information, this will be fixed by renovation.
https://gist.github.com/spf-tanabe/3dd5d914d0f341ba8b9486db80b979af

* Since I do not have permission to pull request, I will provide a patch.
* This patch may not be the best refurbishment because the following inconsistency has occurred in the current code.
  *  It seems that SwScale was deleted from FMJPlugInConfiguration.CUSTOM_CODECS.
  *  Manager.createProcessor () sets SwScale with setCodecChain.
* Refurbishment confirmation can be done with the following code.
```
public class TestVideo {

	public static void main(String[] args) {
		LibJitsi.start();
		List<MediaDevice> devices = ((MediaServiceImpl) LibJitsi.getMediaService()).getDevices(MediaType.VIDEO, MediaUseCase.CALL);
		MediaDevice device = devices.get(0);

		JFrame f = new JFrame();
		Component comp = (Component) LibJitsi.getMediaService().getVideoPreviewComponent(device, 640, 480);
		f.getContentPane().add(comp, BorderLayout.CENTER);
		f.pack();
		f.setVisible(true);
	}
}
```
Thank you.

**Comment by ibauersachs** [comment]
The SwScale 'codec' cannot go back to the default list, since that would make loading FFmpeg for the entire libjitsi mandatory again. However, FFmpeg *is* required for anything related to device access, i.e. the webcam. In your `TestVideo` example above, you need to enabled the FFmpeg codecs by setting the property `org.jitsi.service.neomedia.MediaService.ENABLE_FFMPEG_CODECS=true`. In the example, you could call `LibJitsi.getConfigurationService().setProperty(...)` just after `start()`.

Let us know what happens then.

**Comment by traud** [comment]
Mhm. For me it is just the preview (in Options and while in a call) which does not work. Sending of the camera image works. Please, start Jitsi Desktop from the command prompt. Do you get an Java exception related to HFlip with code -22? Then this issue here is related to jitsi/jitsi#540.
