### ISSUE TITLE
libjnvpx doesn't compile against the latest libvpx

### ISSUE THREAD

**Issue by bgrozev** [jitsi/libjitsi#44]
It fails to find vpx_codec_mmap_t and vpx_codec_{get,set}_mem_map. They were probably (re)moved at some point in libvpx. We should update our code accordingly.

**Comment by Manizuca** [comment]
all the relevant commits are here:
https://gerrit.chromium.org/gerrit/gitweb?p=webm%2Flibvpx.git&a=search&h=HEAD&st=commit&s=+XMA
