### ISSUE TITLE
DTLS 1.2 handshake Alert Protocol Version

### ISSUE THREAD

**Issue by nileshzarkar** [jitsi/libjitsi#444]
## Description
I am trying to write a webRTC client for cafeX. and using libjitsi (version available as of 23 Oct 2018) for the media transmission using DTLS-SRTP (as recommended by webRTC)
Following below steps for establishing call
1. SIP Signalling (with cafeX WegGateway)
2. STUN handshake (with cafeX Media Broker)
3. DTLS handshake  (with cafeX Media Broker)

I am facing issue in DTLS handshake while using DTLS1.2. Does libjitsi support DTLSV1.2 on **server side** and **client side** ?
The reason I ask this because in code TlsServerImpl the default max and min version is hardcoded to 
ProtocolVersion.DTLSv10.

1. My client code is acting as Server. So U get Client Hello from cafeX Media Broker
2. I respond with Server Hello
3. Media Broker responds back to me with Alert Protocol Version fatal level Alert.

**Attached are the application logs and the wireshark packet messages.**

[application log file.txt](https://github.com/jitsi/libjitsi/files/2503006/application.log.file.txt)

[ClientHello_wireshark.txt](https://github.com/jitsi/libjitsi/files/2503014/ClientHello_wireshark.txt)
[ProtocolVersionAlert_wireshark.txt](https://github.com/jitsi/libjitsi/files/2503015/ProtocolVersionAlert_wireshark.txt)
[ServerHello_wireshark.txt](https://github.com/jitsi/libjitsi/files/2503016/ServerHello_wireshark.txt)

The bouncy castle jars version it is using (configured in maven is 1.55 version)

What should I do to make this work ?

##Current behavior

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by bbaldino** [comment]
Just want to add: I was looking at the DTLS code a lot for the libjitsi re-write and noticed that I believe the bouncycastle APIs we're using are also a bit old/outdated and technically deprecated in favor of new APIs.  I didn't use the new APIs in the rewrite to keep the changes to a minimum, but I think it's something we should look into.  I don't know if the current ones preclude us from using v1.2 (I think 1.1 was hard-coded at the time to keep things simpler), but certainly if we take a look at updating the bouncycastle APIs that would likely be a good time to look at v1.2 (though we don't necessarily need to wait for that to look into 1.2).  

If you want to try changing the max version and seeing how things go, that would be the place to start I think.

**Comment by ibauersachs** [comment]
DTLS 1.2 added in #539
