### ISSUE TITLE
OpenSSL upgrade to newer version.

### ISSUE THREAD

**Issue by mstyura** [jitsi/libjitsi#446]
Currently `libjitsi` uses very old version of `OpenSSL 1.0.1k` ([released 8 Jan 2015](https://web.archive.org/web/20150120120428/https://www.openssl.org/news/openssl-1.0.1-notes.html)).

Latest update in `libjitsi` were [happen in 2016](https://github.com/jitsi/libjitsi/commit/ad264113a7e31642379144d8b609d23daa4d2930).
Newer version of Linux distros like CentOS 7.5 does not have any kind of ` libcrypto.so.1.0.0`, so `videobridge` silently fallback to `BouncyCastle` implementation, which seems to be slower than `OpenSSL`.

An upgrade of `OpenSSL` is required due to multiple reasons:
1. Absence of old version of `OpenSSL` in moder distros, which hurts performance.
2. Presence of [many vulnerabilities](https://www.cvedetails.com/vulnerability-list/vendor_id-217/product_id-383/version_id-180645/Openssl-Openssl-1.0.1k.html) in `OpenSSL 1.0.1k` versions.

**Comment by mstyura** [comment]
Good day, @damencho!

Could you please take a looks at this and if possible re-build `libjnopenssl.so` 🙏 ?

Thank you very much in advance, Дамян!

**Comment by Neustradamus** [comment]
Actually the last OpenSSL version is 1.1.1a.

**Comment by mstyura** [comment]
@Neustradamus the #454 actually can be compiled against `1.1.1a` as well... but someone will have to re-build `JNI` wrapper which I've fixed in #454, but I'm untrusted and unrelated to Jitsi person I can't provide pre-built binary `JNI` wrapper for crypto library in my PR. So, maybe someone from Jitsi will continue work and actually re-build wrapper library for #454.

**Comment by bbaldino** [comment]
I'll throw out that I'd like to split out the jniwrapper work for openssl into a separate repo like I did for [sctp4j](https://github.com/jitsi/sctp4j) this way it'll be easier to manage/update (and easier to depend on).

**Comment by bbaldino** [comment]
> @bbaldino If you do this, have you considered using Gradle's C support to use just one build system for both Java and the native part?

No, I wasn't aware of this but we'd first have to move to gradle--which I'd be up for but would be a big change.  I've been using the maven-native-plugin so at least sctp4j is now maven-ized.

> Plus, Wildfly has an OpenSSL library that might be of use. I'm not sure what exactly is in there, but it's worth taking a look, we could potentially avoid maintaining this ourselves.

Yeah that'd be great, looks like they've got a lib on maven already.

**Comment by ibauersachs** [comment]
> we'd first have to move to gradle
Not for libjitsi, only for the new potential "libjitsi-openssl" lib.

**Comment by bbaldino** [comment]
> Not for libjitsi, only for the new potential "libjitsi-openssl" lib.

Oh I see, yeah that'd be worth looking into if we can't use wildfly.

**Comment by ibauersachs** [comment]
Openssl is no longer directly used by libjitsi
