### ISSUE TITLE
Rename the jabber to xmpp

### ISSUE THREAD

**Issue by Neustradamus** [jitsi/libjitsi#458]
It is XMPP since 2004, 20yo since 19/01/04: https://xmpp.org/
- https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/service/packetlogging/PacketLoggingConfiguration.java
- https://github.com/jitsi/libjitsi/blob/master/src/org/jitsi/service/packetlogging/PacketLoggingService.java

**Comment by damencho** [comment]
What do you mean?

Please discuss questions and problems on the community forum, before opening new issues, thank you.

**Comment by Neustradamus** [comment]
Replace jabber to xmpp in code, easy (very little in libjitsi).
Why have you already closed this ticket?

**Comment by damencho** [comment]
I closed the ticket cause it lacks information in its initial state. Renaming jabber to xmpp is a big refactoring, which affects not only libjitsi, but also and Jitsi Desktop and Jigasi and needs some extra code for not breaking everybody's installations and deployments. In other words, this is not a just replace in a text file operation, so I don't see it coming soon if we don't see some PRs addressing all those.

**Comment by ibauersachs** [comment]
Thanks @Damencho.
Btw, before anybody tackles bigger refactorings in Jitsi, please let me know. I'm currently working on moving the source folder into separate, proper (Maven structured) submodules, plus building the whole thing with Gradle, auto-generate the manifests, etc. for proper OSGi support in the IDE.

**Comment by Neustradamus** [comment]
@emcho, @damencho, ibauersachs: Who can update the code?

**Comment by damencho** [comment]
@ibauersachs I doubt anybody will work on this anytime soon.

**Comment by ibauersachs** [comment]
I've touched these classes anyway to move the enums to their own files, I'll have a look.

**Comment by Neustradamus** [comment]
@ibauersachs: Any news since 4 months?
