### ISSUE TITLE
How to compile to MIPS platform

### ISSUE THREAD

**Issue by guozhichao** [jitsi/libjitsi#490]
Hi,

I am now in MIPS platform, I want to know how to build lib of MIPS platform

**Comment by cnscns** [comment]
Have you compiled on android armeabi?

**Comment by guozhichao** [comment]
> Have you compiled on android armeabi?

I haven't compiled on android

**Comment by guozhichao** [comment]
I've solved this problem by compiling it from the source code for libjitsi
