### ISSUE TITLE
How to compile jni for android

### ISSUE THREAD

**Issue by cnscns** [jitsi/libjitsi#491]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by damencho** [comment]
Please, when you have questions use the community forum before opening new issues.

Android is not supported.
