### ISSUE TITLE
bug in org.jitsi.impl.neomedia.transform.TransformEngineChain#addEngine

### ISSUE THREAD

**Issue by fabvador** [jitsi/libjitsi#50]
the function 

      org.jitsi.impl.neomedia.transform.TransformEngineChain 
      public boolean addEngine(TransformEngine engine)

is faulty. It does not do anything.
Should be modified

**Comment by bgrozev** [comment]
Thanks, I believe this is fixed now.

**Comment by fabvador** [comment]
Cool!
