### ISSUE TITLE
org.jitsi.impl.neomedia.MediaStreamImpl field transformEngineChain should be accessible

### ISSUE THREAD

**Issue by fabvador** [jitsi/libjitsi#51]
In the view of creating my custom AudioMediaStream which inherits from AudioMediaStreamImpl,
I need a way to modify the 'transformEngineChain'.
Unfortunatelly, this is a private field and no get method exist!
I suggest to create a public getTransformEngineChain method!

**Comment by fabvador** [comment]
I have modified the source. It is already pushed!

**Comment by bgrozev** [comment]
Our intent is to use MediaStream#setExternalTransformer(TransformEngine transformEngine) to add your application-specific transformers in such cases. You can add a whole TransformEngineChain as well (which [we do in jitsi-videobridge](https://github.com/jitsi/jitsi-videobridge/blob/master/src/org/jitsi/videobridge/RtpChannel.java#L906)). Do you have a use-case for which this doesn't work?

**Comment by fabvador** [comment]
Super!
Sorry, I was not aware!
Another question, How do I had a codec in the process stack?


Thx

**Comment by bgrozev** [comment]
See the code under org.jitsi.impl.neomedia.codec. You can use opus as an example.
