### ISSUE TITLE
Libjitsi libjitsi-626-i386 screen sharing issue

### ISSUE THREAD

**Issue by JohnReedLOL** [jitsi/libjitsi#52]
I have had this occur twice. First time:

While trying to screen share from Ubuntu Linux 32 bit to Windows 7 64 bit using Libjitsi version:
libjitsi-626-i386.zip   2015-06-12 21:11   11M

Java path is: /home/john/Programs/jdk1.8.0_45/jre/bin/java

OS: Linux

Architecture: i386

...

H264 90000.0
Jun 13, 2015 6:50:19 PM org.jitsi.util.Logger info
INFO: video send FPS: 10.0
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log info
INFO: Resetting queue, last seq added: 9223372036854775806, current seq: 36772
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log info
INFO: Starting RTPSourceStream.
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log error
SEVERE: Failed to realize: net.sf.fmj.media.ProcessEngine@1a11e02
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log error
SEVERE:   Cannot build a flow graph with the customized options:
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log error
SEVERE:     Unable to transcode format: AVFRAME, 1600x1200, class org.jitsi.impl.neomedia.codec.video.AVFrame, pixFmt 27
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log error
SEVERE:       to: H264/RTP, fmtps={packetization-mode=1}
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log error
SEVERE:       outputting to: raw.rtp
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log error
SEVERE:     Unable to add customed codecs:
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log error
SEVERE:       org.jitsi.impl.neomedia.codec.video.h264.JNIEncoder@18b328b
Jun 13, 2015 6:50:19 PM org.jitsi.util.Logger info
INFO: Stop stream
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log error
SEVERE: Error: Unable to realize net.sf.fmj.media.ProcessEngine@1a11e02
Jun 13, 2015 6:50:19 PM org.jitsi.util.Logger warn
WARNING: javax.media.ResourceUnavailableEvent[source=com.sun.media.processor.unknown.Handler@16b76da,message=Failed to realize: cannot handle the customized options set on the Processor.
Check the logs for full details.]
Jun 13, 2015 6:50:19 PM org.jitsi.util.Logger warn
WARNING: ControllerErrorEvent: javax.media.ResourceUnavailableEvent[source=com.sun.media.processor.unknown.Handler@16b76da,message=Failed to realize: cannot handle the customized options set on the Processor.
Check the logs for full details.]
Jun 13, 2015 6:50:19 PM org.jitsi.util.Logger warn
WARNING: javax.media.ControllerClosedEvent[source=com.sun.media.processor.unknown.Handler@16b76da]
Jun 13, 2015 6:50:19 PM org.jitsi.util.Logger info
INFO: video codec/freq: H264/90000 Hz
Jun 13, 2015 6:50:19 PM org.jitsi.util.Logger info
INFO: video remote IP/port: 192.168.10.100/15000
Jun 13, 2015 6:50:19 PM net.sf.fmj.media.Log info
INFO: Starting RTPSourceStream.

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:205)
videoMediaStream_ started.

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:209)
videoDevice name2: Desktop Streaming 0

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:210)
videoDevice toString2: Desktop Streaming 0 : imgstreaming:0
AVFRAME, 1600x1200, class org.jitsi.impl.neomedia.codec.video.AVFrame, pixFmt 27
RGB, 1600x1200, 32-bit, Masks=2:3:4, PixelStride=4, LineStride=6400

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:211)
Frame rate: -1

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:212)
Video bitrate: 128

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:213)
RTP Pacing Threshold: 256

Second time:

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:141)
videoDevice toString: Desktop Streaming 0 : imgstreaming:0
AVFRAME, 1600x1200, class org.jitsi.impl.neomedia.codec.video.AVFrame, pixFmt 27
RGB, 1600x1200, 32-bit, Masks=2:3:4, PixelStride=4, LineStride=6400

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:142)
Frame rate: -1

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:143)
Video bitrate: 128

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:144)
RTP Pacing Threshold: 256

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:145)
Video size: java.awt.Dimension[width=640,height=480]

In thread Stun4J Message Processor: Core.VideoStreamer.getH264(VideoStreamer.java:271)
Number of video formats: 2

In thread Stun4J Message Processor: Core.VideoStreamer.getH264(VideoStreamer.java:275)
H264 90000.0
Jun 14, 2015 2:50:44 PM org.jitsi.util.Logger info
INFO: video send FPS: 10.0
Jun 14, 2015 2:50:44 PM net.sf.fmj.media.Log info
INFO: Resetting queue, last seq added: 9223372036854775806, current seq: 59795
Jun 14, 2015 2:50:44 PM net.sf.fmj.media.Log info
INFO: Starting RTPSourceStream.
Jun 14, 2015 2:50:45 PM net.sf.fmj.media.Log error
SEVERE: Failed to realize: net.sf.fmj.media.ProcessEngine@1f148fa
Jun 14, 2015 2:50:45 PM net.sf.fmj.media.Log error
SEVERE:   Cannot build a flow graph with the customized options:
Jun 14, 2015 2:50:45 PM net.sf.fmj.media.Log error
SEVERE:     Unable to transcode format: AVFRAME, 1600x1200, class org.jitsi.impl.neomedia.codec.video.AVFrame, pixFmt 27
Jun 14, 2015 2:50:45 PM net.sf.fmj.media.Log error
SEVERE:       to: H264/RTP, fmtps={packetization-mode=1}
Jun 14, 2015 2:50:45 PM net.sf.fmj.media.Log error
SEVERE:       outputting to: raw.rtp
Jun 14, 2015 2:50:45 PM net.sf.fmj.media.Log error
SEVERE:     Unable to add customed codecs: 
Jun 14, 2015 2:50:45 PM net.sf.fmj.media.Log error
SEVERE:       org.jitsi.impl.neomedia.codec.video.h264.JNIEncoder@11d02d4
Jun 14, 2015 2:50:45 PM org.jitsi.util.Logger info
INFO: Stop stream
Jun 14, 2015 2:50:45 PM net.sf.fmj.media.Log error
SEVERE: Error: Unable to realize net.sf.fmj.media.ProcessEngine@1f148fa
Jun 14, 2015 2:50:45 PM org.jitsi.util.Logger warn
WARNING: javax.media.ResourceUnavailableEvent[source=com.sun.media.processor.unknown.Handler@92014,message=Failed to realize: cannot handle the customized options set on the Processor.
Check the logs for full details.]
Jun 14, 2015 2:50:45 PM org.jitsi.util.Logger warn
WARNING: ControllerErrorEvent: javax.media.ResourceUnavailableEvent[source=com.sun.media.processor.unknown.Handler@92014,message=Failed to realize: cannot handle the customized options set on the Processor.
Check the logs for full details.]
Jun 14, 2015 2:50:45 PM org.jitsi.util.Logger warn
WARNING: javax.media.ControllerClosedEvent[source=com.sun.media.processor.unknown.Handler@92014]
Jun 14, 2015 2:50:45 PM org.jitsi.util.Logger info
INFO: video codec/freq: H264/90000 Hz
Jun 14, 2015 2:50:45 PM org.jitsi.util.Logger info
INFO: video remote IP/port: 192.168.10.100/15000
Jun 14, 2015 2:50:45 PM net.sf.fmj.media.Log info
INFO: Starting RTPSourceStream.

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:205)
videoMediaStream_ started.

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:209)
videoDevice name2: Desktop Streaming 0

In thread Stun4J Message Processor: Core.VideoStreamer.startVideoStream(VideoStreamer.java:210)
videoDevice toString2: Desktop Streaming 0 : imgstreaming:0
AVFRAME, 1600x1200, class org.jitsi.impl.neomedia.codec.video.AVFrame, pixFmt 27
RGB, 1600x1200, 32-bit, Masks=2:3:4, PixelStride=4, LineStride=6400

**Comment by ibauersachs** [comment]
Did you develop a custom application that uses libjitsi? Otherwise please send your issue with more details on what you did (or were trying to do), including your account types and environment, to users@jitsi.org.

**Comment by JohnReedLOL** [comment]
> Did you develop a custom application that uses libjitsi?
Kinda. All I did was stream my desktop from one computer in my apartment to another computer in the same apartment (local network). And on rare occasions, I would get this exception.

**Comment by ibauersachs** [comment]
Not sure what to do with this. AFAIK nobody is working on the screensharing and I have no clue what's going on there.
