### ISSUE TITLE
SRTP protocol

### ISSUE THREAD

**Issue by ctriz** [jitsi/libjitsi#523]
i understand that jitsi uses DLTS-SRTP. i recentlt installed jitsi server successfully in a LAN setup.
I was able to have a video conferencing using the chrome browser using the jitsi server. I collected the traffic at the server. However, when i open it using wireshark, it is not showing the media packets on port 10000 as RTP. Am i missing something here?

**Comment by bgrozev** [comment]
You need to configure wireshark to interpret packets on port 10000 as RTP.
