### ISSUE TITLE
There is no source code of jnffmpeg jnopus and so on

### ISSUE THREAD

**Issue by cnscns** [jitsi/libjitsi#524]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by ibauersachs** [comment]
**jnffmpeg**
Repo: https://github.com/jitsi/jitsi-lgpl-dependencies

**jnopus**
- Source: https://github.com/jitsi/libjitsi/tree/master/src/native/opus
- Build instructions: https://github.com/jitsi/libjitsi/blob/master/src/native/build.xml#L683
