### ISSUE TITLE
loudspeaker and headset

### ISSUE THREAD

**Issue by fabvador** [jitsi/libjitsi#53]
I would like to have audio input (coming from RTP stream) simultaneously on loudspeaker and headset.
Is that possible?

**Comment by fabvador** [comment]
I think I have to customize the FMJ 'processor'.
Am I right?

**Comment by damencho** [comment]
Yes it is possible. We had added an option to play notifications simultaneously on notification device which can be the loadspeaker and on the playback device - the headset. You can take a look in that direction and patches are welcome.
