### ISSUE TITLE
Source code for the FFmpeg binary

### ISSUE THREAD

**Issue by Cigaes** [jitsi/libjitsi#532]
Hi.
The directory `lib/native/` contains pre-built binaries statically linked with FFmpeg and x264, with a GPLv3 license.
But you do not include the source code for FFmpeg, nor a written offer for it: you are therefore violating article 6 “Conveying Non-Source Forms” of the GPL. Please fix it.

**Comment by bgrozev** [comment]
Thanks for bringing this up. These are [removed now](https://github.com/jitsi/libjitsi/pull/533) (they were not used in any way).
