### ISSUE TITLE
Unable to use libjitsi for audio streaming to an IP address and port

### ISSUE THREAD

**Issue by nabhonil** [jitsi/libjitsi#556]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
hi,

I am trying to build a Java application which will stream audio to a particular IP address and Port number. I am using the libjitsi-1.1-4-gfb6b03ff.jar. Whenever my code execute the following lines
LibJitsi. start ();
MediaService mediaService = LibJitsi. getMediaService ();
I keep getting exceptions INFO: Failed to load CoreAudioDevice library: java.lang.UnsatisfiedLinkError: no jnmaccoreaudio in java.library.path

I have downloaded the libjitsi jar from the mvn repository. Do i need to download any more libraries and include them? Are they available anywhere to download?
Or
Should I check out the entire github repo for the libjitsi and create a build for the respective platform e.g linux or windows? Any steps how to do that?

Please help
Thanks
Nabhonil

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by nabhonil** [comment]
Thank you Bgrozev, 

Just wanted to know one more thing, is this darwin/*.dylib will work in the Linux also or do I need to have separate library for linux, i mean darwin/*.so files for Linux?

**Comment by damencho** [comment]
darwin is for macos

**Comment by nabhonil** [comment]
Any idea where i can get these libraries for Linux as my application will run in Linux?

**Comment by nabhonil** [comment]
Ignore my comments above it is available in the jar. Thanks for all the help.
