### ISSUE TITLE
Project 'libjitsi' is missing required library: 'lib/jspeex.jar'	?

### ISSUE THREAD

**Issue by Lycoriso** [jitsi/libjitsi#56]
Project 'libjitsi' is missing required library: 'lib/jspeex.jar'	?

**Comment by lyubomir** [comment]
lib/jspeex.jar should no longer be required. If the Eclipse .classpath file
says it is required, I can fix it on Monday. In the meantime, it should be
sufficient to delete lib/jspeex.jar from the Eclipse .classpath file.

**Comment by Lycoriso** [comment]
ok,thank you.
