### ISSUE TITLE
support mac m1?

### ISSUE THREAD

**Issue by shushenghong** [jitsi/libjitsi#561]
Did this great library support mac m1?

**Comment by luca992** [comment]
<img width="316" alt="Screen Shot 2022-11-07 at 5 14 08 PM" src="https://user-images.githubusercontent.com/4157455/200426849-b6f79f73-dc9b-4fdf-95e5-2cad38489c2a.png">
Doesn't look like it yet 😔

**Comment by csett86** [comment]
Yes, it does since #564:

<img width="227" alt="Bildschirmfoto 2024-11-04 um 22 58 28" src="https://github.com/user-attachments/assets/dd916ad9-800a-435d-b5f8-77d46a9be362">
