### ISSUE TITLE
Outgoing G722 RTP packets have incorrect RTP timestamp

### ISSUE THREAD

**Issue by cspiel1** [jitsi/libjitsi#57]
First G722 rtp packet has timestamp 2^32-1.

I found the fix in jitsi repo for bug #872 (see below), and saw that "outputFormat =" is missing for G722 in (src/org/jitsi/impl/neomedia/codec/audio/g722/JNIEncoderImpl.java:118). I can not build and verify this. So maybe someone is able to try this.

regards,
chris.

```
diff --git a/src/net/java/sip/communicator/impl/neomedia/codec/audio/speex/JNIEncoder.java b/s
index f0cd63e..3804bfe 100644
--- a/src/net/java/sip/communicator/impl/neomedia/codec/audio/speex/JNIEncoder.java
+++ b/src/net/java/sip/communicator/impl/neomedia/codec/audio/speex/JNIEncoder.java
@@ -413,7 +413,7 @@ public class JNIEncoder
         {
             AudioFormat outputAudioFormat = (AudioFormat) outputFormat;
 
-            setOutputFormat(
+            outputFormat = setOutputFormat(
                 new AudioFormat(
                             outputAudioFormat.getEncoding(),
                             outputAudioFormat.getSampleRate(),
@@ -425,6 +425,8 @@ public class JNIEncoder
                             outputAudioFormat.getFrameRate(),
                             outputAudioFormat.getDataType())
                         {
+                            private static final long serialVersionUID = 0L;
+
                             @Override
                             public long computeDuration(long length)
                             {
```

**Comment by bgrozev** [comment]
I think that a similar change to the G722 encoder makes sense, since we don't want to return a stale value. But I don't know if this will have an effect the RTP timestamps.

In anyway, [according to RFC3550](http://tools.ietf.org/html/rfc3550#page-15), the initial timestamp should be chosen at random, so I don't see how changing it from 2^32-1 to 0 will solve any issues.

**Comment by cspiel1** [comment]
It seems that ignoring this faulty packet on the remote side solves it for
linphone, which uses libortp. We had the issue that audio playback was
muted for the first approximately 8 seconds.
Am 08.09.2015 5:52 nachm. schrieb "bgrozev" <notifications@github.com>:

**Comment by bgrozev** [comment]
Sounds like a problem on the linphone side. Using 2^32-1 for the timestamp does not make a packet faulty.
