### ISSUE TITLE
Enable libjitsi logging

### ISSUE THREAD

**Issue by AtulyaAgg** [jitsi/libjitsi#575]
Could anyone help on how to enable logging in libjitsi when enabling transcription in jitsi/jigasi. I have made logging.properties but it does not seem to work.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Share your logging properties file.

**Comment by damencho** [comment]
community.jitsi.org
It is in the template of when creating issues.

**Comment by damencho** [comment]
Your console hanlder will show just Info you need to change that 
java.util.logging.ConsoleHandler=INFO
