### ISSUE TITLE
Renaming Problems 

### ISSUE THREAD

**Issue by jamesbond12** [jitsi/libjitsi#59]
I want to compile and build libjitsi for com.example on Android .  But when I include the renamed jar, it has errors.
I renamed from org.jitsi to com.example using Ideal J but it shows errors 

What is the best to use libjitsi for a custom application?

**Comment by ibauersachs** [comment]
You can't simply rename the package(s), the native library bindings would need to be adapted and some classes use reflection based on hard names. There's no reason to rename libjitsi, it won't show up in your application's name. Take a look at [jitsi-android](https://github.com/jitsi/jitsi-android) on how to use libjitsi on Android.
