### ISSUE TITLE
ScreenCapture.grabScreen fills byte array with all -1

### ISSUE THREAD

**Issue by BenjaminFaal** [jitsi/libjitsi#70]
When i use the grabScreen method it fills my byte array with -1

What am i doing wrong?

						Rectangle rect = new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
						int width = rect.width;
						int height = rect.height;
						int size = width * height * 4;
						while (true)
						{
							byte[] bytes = new byte[size];
							boolean success = ScreenCapture.grabScreen(displayIndex, 0, 0, width, height, bytes);
							// do something with the byte array
						}

**Comment by BenjaminFaal** [comment]
Now i got it to work but i need to send it to android by a socket and read it as bitmap any ideas?

**Comment by ibauersachs** [comment]
As this isn't about a problem in libjitsi, please seek help in a Java forum.
