### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by mondain** [jitsi/libjitsi#74]
The latest version wont build in Maven.
```sh
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/mondain/workspace/github/libjitsi/src/org/jitsi/impl/neomedia/transform/rtcp/StatisticsEngine.java:[603,50] error: cannot find symbol
```

**Comment by dwilson6** [comment]
We saw a similar issue yesterday. A new version of FMJ seems to be the culprit. A temporary fix is to clone jitsi-universe and change the FMJ version from 1.0-SNAPSHOT to a specific artifact (you can find them in the jitsi-maven-repository repo). I have a branch in my fork which has the version of fmj that works. https://github.com/pstros/jitsi-universe/tree/rt-compatible-deps?files=1

If you clone it and check out that branch and then do a mvn install in jitsi-universe then you should be able to build libjitsi

**Comment by bgrozev** [comment]
Ops, I broke that. Will fix, thanks for reporting!

**Comment by mondain** [comment]
Thanks for the workaround and yes, I noticed its an FMJ issue. The fmj snapshot doesnt have the getRoundTripDelay method in RecvSSRInfo.

From StatisticsEngine:
```java
            voipMetrics.setRoundTripDelay(
                    ((RecvSSRCInfo) receiveStream).getRoundTripDelay(
                            senderSSRC));
```
