### ISSUE TITLE
Static link libvpx in libjnvpx

### ISSUE THREAD

**Issue by damencho** [jitsi/libjitsi#9]
Make sure we statically link libvpx into binary libjnvpx, as the lib is not detected when building binary debian package and breaks the process.

**Comment by stokito** [comment]
I'm tried to make it but failed 
I extracted libvpx binding to separate project and mavenized it with Maven NAR Plugin
https://github.com/stokito/libjnvpx

**Comment by damencho** [comment]
Thanks @stokito. Will close this one as currently is not causing any issues and is working fine, if we need  will reopen it.
